### ISSUE TITLE
点击支付提示fail invalid appid

### ISSUE THREAD

**Issue by tangniyuqi** [pysnow530/wechat-payment#2]
怎么回事呢？ 预支付id也是生成成功的

**Comment by pysnow530** [comment]
把内容再整理一下贴过来给后来的人做参考
这个是微信的错误提示，你看看appid有没有问题，每个接口参数传什么值应该没问题吧？
不知道这个问题最后有没有找到原因？找到了请告诉鄙人一下 :-)
